package com.ah.be.simulate;

public class SimulateConstant {

	static public final int SIMULATE_DATATYPE_INCREASE = 0;
	static public final int SIMULATE_DATATYPE_SET = 1;
	
	/**
	 * this array include data type,data length, range,min
	 */
	static public int[][] SIMULATE_VIFSTATS_BASE = {
			 {SIMULATE_DATATYPE_INCREASE,4,5000,5000}//RxVIfDataFrames
			,{SIMULATE_DATATYPE_INCREASE,4,4000,4000}//RxVIfUnicastDataFrames
			,{SIMULATE_DATATYPE_INCREASE,4,200,200}//RxVIfMulticastDataFrames
			,{SIMULATE_DATATYPE_INCREASE,4,100,100}//RxVIfBroadcastDataFrames
			,{SIMULATE_DATATYPE_INCREASE,4,100,0}//RxVIfErrorFrames
			,{SIMULATE_DATATYPE_INCREASE,4,100,0}//RxVIfDroppedFrames
			
			,{SIMULATE_DATATYPE_INCREASE,4,5000,5000}//TxVIfDataFrames
			,{SIMULATE_DATATYPE_INCREASE,4,4000,4000}//TxVIfUnicastDataFrames
			,{SIMULATE_DATATYPE_INCREASE,4,200,200}//TxVIfMulticastDataFrames
			,{SIMULATE_DATATYPE_INCREASE,4,100,100}//TxVIfBroadcastDataFrames
			,{SIMULATE_DATATYPE_INCREASE,4,100,0}//TxVIfErrorFrames
			,{SIMULATE_DATATYPE_INCREASE,4,100,0}//TxVIfDroppedFrames
			
			,{SIMULATE_DATATYPE_INCREASE,4,200,200}//TxVIfMulticastDataFrames
			,{SIMULATE_DATATYPE_INCREASE,4,200,200}//TxVIfBroadcastDataFrames
			,{SIMULATE_DATATYPE_INCREASE,4,100,0}//TxVIfErrorFrames
			,{SIMULATE_DATATYPE_INCREASE,4,100,0}//TxVIfDroppedFrames
			
			,{SIMULATE_DATATYPE_INCREASE,8,500000,1000000}//RxVifAirtime
			,{SIMULATE_DATATYPE_INCREASE,8,500000,1000000}//TxVifAirtime
	};
	
	/**
	 * this array include data type,data length, range,min
	 */
	static public int[][] SIMULATE_RADIOATTRIBUTE_BASE = {
			 {SIMULATE_DATATYPE_SET,4,150,-150}//noisefloor
	};
	
	/**
	 * this array include data type,data length, range,min
	 */
	static public int[][] SIMULATE_RADIOSTATS_BASE = {
			 {SIMULATE_DATATYPE_INCREASE,4,5000,5000}//TxDataFrames
			,{SIMULATE_DATATYPE_INCREASE,4,400,400}//TxNonBeaconMgtFrames
			,{SIMULATE_DATATYPE_INCREASE,4,300,300}//TxUnicastDataFrames
			,{SIMULATE_DATATYPE_INCREASE,4,200,200}//TxMulticastDataFrames
			,{SIMULATE_DATATYPE_INCREASE,4,100,100}//TxBroadcastDataFrames
			,{SIMULATE_DATATYPE_INCREASE,4,100,100}//TxBeaconFrames
			,{SIMULATE_DATATYPE_INCREASE,4,100,0}//TxTotalRetries
			,{SIMULATE_DATATYPE_INCREASE,4,100,0}//TxTotalFramesDropped
			,{SIMULATE_DATATYPE_INCREASE,4,100,0}//TxTotalFrameErrors
			,{SIMULATE_DATATYPE_INCREASE,4,100,0}//TxUnicastDataFrames
			
			,{SIMULATE_DATATYPE_INCREASE,4,5000,5000}//RxTotalDataFrames
			,{SIMULATE_DATATYPE_INCREASE,4,400,400}//RadioRxUnicastDataFrames
			,{SIMULATE_DATATYPE_INCREASE,4,300,300}//RxMulticastDataFrames
			,{SIMULATE_DATATYPE_INCREASE,4,200,200}//RxBroadcastDataFrames
			,{SIMULATE_DATATYPE_INCREASE,4,100,100}//RxMgtFrames
			,{SIMULATE_DATATYPE_INCREASE,4,100,0}//RxTotalFrameDropped
			
			,{SIMULATE_DATATYPE_INCREASE,4,100,0}//TxBeDataFrames
			,{SIMULATE_DATATYPE_INCREASE,4,100,0}//TxBgDataFrames
			,{SIMULATE_DATATYPE_INCREASE,4,1000,1000}//TxViDataFrames
			,{SIMULATE_DATATYPE_INCREASE,4,100,0}//TxVoDataFrames
			,{SIMULATE_DATATYPE_INCREASE,4,100,0}//TXRTSFailures
			
			,{SIMULATE_DATATYPE_INCREASE,8,500000,1000000}//RxAirtime
			,{SIMULATE_DATATYPE_INCREASE,8,500000,1000000}//TxAirtime
			,{SIMULATE_DATATYPE_SET,4,160000,600}//BandWidth
	};
	
	/**
	 * this array include data type,data length, range,min
	 */
	static public int[][] SIMULATE_NEIGHBOR_BASE = {
			 {SIMULATE_DATATYPE_SET,4,100,0}//LinkCost
			,{SIMULATE_DATATYPE_SET,4,100,0}//Rssi
			,{SIMULATE_DATATYPE_INCREASE,4,5000,5000}//RxDataFrames
			,{SIMULATE_DATATYPE_INCREASE,4,5000,5000}//RxDataOctets
			,{SIMULATE_DATATYPE_INCREASE,4,200,200}//RxMgtFrames
			,{SIMULATE_DATATYPE_INCREASE,4,200,200}//RxUnicastFrames
			,{SIMULATE_DATATYPE_INCREASE,4,100,0}//RxMulticastFrames
			,{SIMULATE_DATATYPE_INCREASE,4,100,0}//RxBroadcastFrames
			
			,{SIMULATE_DATATYPE_INCREASE,4,5000,5000}//TxDataFrames
			,{SIMULATE_DATATYPE_INCREASE,4,200,200}//TxMgtFrames
			,{SIMULATE_DATATYPE_INCREASE,4,4000,4000}//TxDataOctets
			,{SIMULATE_DATATYPE_INCREASE,4,100,100}//TxUnicastFrames
			,{SIMULATE_DATATYPE_INCREASE,4,100,0}//TxMulticastFrames
			,{SIMULATE_DATATYPE_INCREASE,4,100,0}//TxBroadcastFrames
			
			,{SIMULATE_DATATYPE_INCREASE,4,200,0}//TxBeDataFrames
			,{SIMULATE_DATATYPE_INCREASE,4,200,0}//TxBgDataFrames
			,{SIMULATE_DATATYPE_INCREASE,4,1000,1000}//TxViDataFrames
			,{SIMULATE_DATATYPE_INCREASE,4,100,0}//TxVoDataFrames
			
	};
	
	/**
	 * this array include data type,data length, range,min
	 */
	static public int[][] SIMULATE_INTERFERENCE_BASE = {
			 {SIMULATE_DATATYPE_SET,1,100,0}//AverageTXCU
			,{SIMULATE_DATATYPE_SET,1,100,0}//AverageRXCU
			,{SIMULATE_DATATYPE_SET,1,25,0}//AverageInterferenceCU
			,{SIMULATE_DATATYPE_SET,1,100,0}//AverageNoiseFloor
			
			,{SIMULATE_DATATYPE_SET,1,100,0}//ShortTermTXCU
			,{SIMULATE_DATATYPE_SET,1,100,0}//ShortTermRXCU
			,{SIMULATE_DATATYPE_SET,1,25,0}//ShortTermInterferenceCU
			,{SIMULATE_DATATYPE_SET,1,100,0}//ShortTermNoiseFloor
				
			,{SIMULATE_DATATYPE_SET,1,100,0}//SnapShotTXCU
			,{SIMULATE_DATATYPE_SET,1,100,0}//SnapShotRXCU
			,{SIMULATE_DATATYPE_SET,1,25,0}//SnapShotInterferenceCU
			,{SIMULATE_DATATYPE_SET,1,100,0}//SnapShotNoiseFloor
			
			,{SIMULATE_DATATYPE_SET,1,25,0}//CrcError
			,{SIMULATE_DATATYPE_SET,1,0,20}//InterferenceCUThreshold
			,{SIMULATE_DATATYPE_SET,1,0,20}//CrcErrorRateThreshold
	};
	
	/**
	 * this array include data type,data length, range,min
	 */
	static public int[][] SIMULATE_ASSOCIATION_BASE = {
			{SIMULATE_DATATYPE_SET,4,100,0}//Rssi
			,{SIMULATE_DATATYPE_SET,4,150,1000}//LastTxRate
			,{SIMULATE_DATATYPE_SET,4,150,1000}//LastRxRate
			,{SIMULATE_DATATYPE_INCREASE,4,5000,5000}//RxDataFrames
			,{SIMULATE_DATATYPE_INCREASE,4,5000,5000}//RxDataOctets
			,{SIMULATE_DATATYPE_INCREASE,4,200,200}//RxMgtFrames
			,{SIMULATE_DATATYPE_INCREASE,4,200,200}//RxUnicastFrames
			,{SIMULATE_DATATYPE_INCREASE,4,100,0}//RxMulticastFrames
			,{SIMULATE_DATATYPE_INCREASE,4,100,0}//RxBroadcastFrames
			,{SIMULATE_DATATYPE_INCREASE,4,100,0}//RxMICFailures
			
			,{SIMULATE_DATATYPE_INCREASE,4,5000,5000}//TxDataFrames
			,{SIMULATE_DATATYPE_INCREASE,4,200,200}//TxMgtFrames
			,{SIMULATE_DATATYPE_INCREASE,4,4000,4000}//TxDataOctets
			,{SIMULATE_DATATYPE_INCREASE,4,100,100}//TxUnicastFrames
			,{SIMULATE_DATATYPE_INCREASE,4,100,0}//TxMulticastFrames
			,{SIMULATE_DATATYPE_INCREASE,4,100,0}//TxBroadcastFrames
			
			,{SIMULATE_DATATYPE_INCREASE,4,200,0}//TxBeDataFrames
			,{SIMULATE_DATATYPE_INCREASE,4,200,0}//TxBgDataFrames
			,{SIMULATE_DATATYPE_INCREASE,4,1000,1000}//TxViDataFrames
			,{SIMULATE_DATATYPE_INCREASE,4,100,0}//TxVoDataFrames
			
			,{SIMULATE_DATATYPE_INCREASE,8,500000,1000000}//RxAirtime
			,{SIMULATE_DATATYPE_INCREASE,8,500000,1000000}//TxAirtime
			
	};
}
