#!/bin/bash
#
# Copyright (C) 2006-2012 Aerohive Networks
#
# yZhong@AeroHive.com
#
##

. $(dirname "$0")/extension

SSHpassword $1
if [ 0 != $? ] ;then
  if [ -z "$2" ] ;then
    exit 1
  fi
  SSHwithOutPassword $1 "$2"
  SSHpassword $1
fi