//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.13 at 11:20:19 AM CST 
//


package com.ah.be.config.cli.xsdbean;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="params" type="{}params-type" minOccurs="0"/>
 *         &lt;element name="cli-gen" type="{}cli-gen-type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="cli-parse" type="{}cli-parse-type" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "params",
    "cliGen",
    "cliParse"
})
@XmlRootElement(name = "clis")
public class Clis {

    protected ParamsType params;
    @XmlElement(name = "cli-gen")
    protected List<CliGenType> cliGen;
    @XmlElement(name = "cli-parse")
    protected List<CliParseType> cliParse;

    /**
     * Gets the value of the params property.
     * 
     * @return
     *     possible object is
     *     {@link ParamsType }
     *     
     */
    public ParamsType getParams() {
        return params;
    }

    /**
     * Sets the value of the params property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParamsType }
     *     
     */
    public void setParams(ParamsType value) {
        this.params = value;
    }

    /**
     * Gets the value of the cliGen property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cliGen property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCliGen().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CliGenType }
     * 
     * 
     */
    public List<CliGenType> getCliGen() {
        if (cliGen == null) {
            cliGen = new ArrayList<CliGenType>();
        }
        return this.cliGen;
    }

    /**
     * Gets the value of the cliParse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cliParse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCliParse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CliParseType }
     * 
     * 
     */
    public List<CliParseType> getCliParse() {
        if (cliParse == null) {
            cliParse = new ArrayList<CliParseType>();
        }
        return this.cliParse;
    }

}
