//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.13 at 11:20:19 AM CST 
//


package com.ah.be.config.cli.xsdbean;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ah.be.config.cli.xsdbean package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ah.be.config.cli.xsdbean
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Clis }
     * 
     */
    public Clis createClis() {
        return new Clis();
    }

    /**
     * Create an instance of {@link ParamsType }
     * 
     */
    public ParamsType createParamsType() {
        return new ParamsType();
    }

    /**
     * Create an instance of {@link CliGenType }
     * 
     */
    public CliGenType createCliGenType() {
        return new CliGenType();
    }

    /**
     * Create an instance of {@link CliParseType }
     * 
     */
    public CliParseType createCliParseType() {
        return new CliParseType();
    }

    /**
     * Create an instance of {@link ConstraintType }
     * 
     */
    public ConstraintType createConstraintType() {
        return new ConstraintType();
    }

    /**
     * Create an instance of {@link ParamType }
     * 
     */
    public ParamType createParamType() {
        return new ParamType();
    }

    /**
     * Create an instance of {@link GroupPostProcessType }
     * 
     */
    public GroupPostProcessType createGroupPostProcessType() {
        return new GroupPostProcessType();
    }

    /**
     * Create an instance of {@link DefaultValueType }
     * 
     */
    public DefaultValueType createDefaultValueType() {
        return new DefaultValueType();
    }

}
